### ISSUE TITLE
With Gnome 3.36, works with xorg, not with wayland (Fedora 32).

### ISSUE THREAD

**Issue by idoric** [emasab/shelltile#99] opened 2020-05-05 20:37 UTC
On Fedora 32, with the default gnome session (which is a wayland session), sheltile does not correctly manage the geometries and positions of the windows, and produces erratic results. But if I select the xorg session, it works perfectly.

**Comment by barnscott** [comment] 2020-05-06 02:45
Same issue. Also using wayland/Fedora 32.

**Comment by GeckoEidechse** [comment] 2020-05-11 14:36
Ubuntu 20.04 with Gnome 36 on Wayland does not work either.

I already noticed an issue on Ubuntu 19.10 with Gnome 34 on Wayland where I couldn't tile windows by dragging one over the other and holding the tile key (`Ctrl` by default). Quarter/vertical tiling by dragging a window to the corner/edge of a screen would still work. This is no longer the case since upgrading to Ubuntu 20.04

**Comment by gnumanx** [comment] 2020-05-13 12:01
Same problem on Archlinux. But if I remove the extension and reinstall it, it works again. I tried to remove the hidden folder under .local, but no impruvements.

**Comment by GeckoEidechse** [comment] 2020-05-13 12:43
I tried reinstalling the extension, however it only fixed tiling by moving the window to the edge/corner of the screen. Tiling by moving one window over the other while holding `Ctrl` still didn't work.

Moreover, after rebooting the functionality was lost again.

**Comment by emasab** [comment] 2020-10-03 11:33
duplicate of

https://github.com/emasab/shelltile/issues/98

**Closed by emasab** 2020-10-03 11:33 UTC
