### ISSUE TITLE
Question: Is this compatible with shell 3.36.4?

### ISSUE THREAD

**Issue by bmccorm2** [emasab/shelltile#102] opened 2020-07-12 18:10 UTC
Apologies in advance for my ignorance, I am running Arch with shell 3.36.4 and I can't get this extension working for the life of me.  I can't find any logs but I have turned off all my other extensions to make sure there is no conflict and it still doesn't work.  I'm not sure how to check which version of the extension i am using but it is whatever is in the arch AUR: https://aur.archlinux.org/packages/gnome-shell-extension-shelltile-git.  Thanks for any help!

**Comment by YsuOS** [comment] 2020-07-22 02:46
I have the same issue on my fedora 32 with gnome-shell 3.36.4. 
I don't know if this is a bug but I use an Edge Tiling feature instead.

**Comment by emasab** [comment] 2020-10-03 11:32
possible duplicate of

https://github.com/emasab/shelltile/issues/98

You should be using Wayland, with Xorg it will work

**Closed** 2020-10-25 11:22 UTC
