### ISSUE TITLE
[Bug] Stop working on Ubuntu 20.04

### ISSUE THREAD

**Issue by maxjf1** [emasab/shelltile#104] opened 2020-08-12 15:28 UTC
Hello, thanks for the great extension.

I was using it normally in Ubuntu 20.04, but after an recent update, it stopped working. 

Demo:

![deepin-screen-recorder_google-chrome_20200812122408](https://user-images.githubusercontent.com/6114888/90034308-d1209500-dc96-11ea-8bb5-555692922e76.gif)

Extension settings:
![image](https://user-images.githubusercontent.com/6114888/90034612-3bd1d080-dc97-11ea-89bd-60fff0ea419d.png)

System info:

```bash
                          ./+o+-       maxjf1@maxjf1-G3-3579
                  yyyyy- -yyyyyy+      OS: Ubuntu 20.04 focal
               ://+//////-yyyyyyo      Kernel: x86_64 Linux 5.4.0-42-generic
           .++ .:/++++++/-.+sss/`      Uptime: 4h 27m
         .:++o:  /++++++++/:--:/-      Packages: 1947
        o:+o+:++.`..```.-/oo+++++/     Shell: zsh 5.8
       .:+o:+o/.          `+sssoo+/    Resolution: 1920x1080
  .++/+:+oo+o:`             /sssooo.   DE: GNOME 3.36.4
 /+++//+:`oo+o               /::--:.   WM: Mutter
 \+/+o+++`o++o               ++////.   WM Theme: Adwaita
  .++.o+++oo+:`             /dddhhh.   GTK Theme: Mojave-dark [GTK2/3]
       .+.o+oo:.          `oddhhhh+    Icon Theme: McMojave-circle-dark
        \+.++o+o``-````.:ohdhhhhh+     Font: Garuda 11
         `:o+++ `ohhhhhhhhyo++os:      Disk: 52G / 79G (69%)
           .o:`.syhhhhhhh/.oo++o`      CPU: Intel Core i5-8300H @ 8x 4GHz [51.0°C]
               /osyyyyyyo++ooo+++/     GPU: Intel Corporation UHD Graphics 630 (Mobile)
                   ````` +oo+++o\:     RAM: 10455MiB / 15858MiB
                          `oo++.      
```

My extensions list:
![image](https://user-images.githubusercontent.com/6114888/90034888-8eab8800-dc97-11ea-8e1c-1f6431c31cdb.png)

**Comment by maxjf1** [comment] 2020-08-13 12:54
After restarting the computer, it works again. Any idea it happened? Something i can check if it happpens again (log files etc)?

**Comment by emasab** [comment] 2020-10-03 11:31
duplicate of

https://github.com/emasab/shelltile/issues/98

You should be using Wayland, with Xorg it will work

**Closed by emasab** 2020-10-03 11:31 UTC
