### ISSUE TITLE
Feature request: Option to change the background color of the grid

### ISSUE THREAD

**Issue by lexruee** [emasab/shelltile#43] opened 2017-07-11 15:41 UTC
@emasab 
First of all, this is a really nice GNOME Shell extension. Well done!

![shelltile-blue-background-part](https://user-images.githubusercontent.com/649340/28076575-7173f79c-665f-11e7-954c-4704730884fe.png)

What do you think about a feature that allows the user to change the background color of the grid.
Currently, the color is set in the stylesheet.css file. I know I can adapt this file to my prefered color, but what about my mom? She doesn't know CSS :smile:.

My proposal is as follows. The prefs.js could be adjusted so that a user can pick the background color and the border color of the grid using a Gtk color chooser widget with some kind of icon paint button.
Here is a mockup for this feature:

![shelltile-mockup](https://user-images.githubusercontent.com/649340/28076584-813a82d6-665f-11e7-9c49-d2f1b43f9258.png)

**Comment by AlexWayfer** [comment] 2017-07-12 16:56
Good proposal! But I think that we can do a choice of one color, and background color and border color will differ in the level of transparency.

**Comment by lexruee** [comment] 2017-07-12 17:42
@AlexWayfer @emasab 
I have implemented a simple prototype for the prefs.js & schema. However, I could not integrate it with extension.js as it would require some refactoring of the code base I guess.
Of course there needs to be a nice slider (Gtk.Hscale) for setting the level of transparency :smile:.

Here are two screenshots that show how the prototype looks:
![screenshot from 2017-07-12 19-36-32](https://user-images.githubusercontent.com/649340/28131277-b3933a7c-6739-11e7-83c1-f3fb6710e712.png)
![screenshot from 2017-07-12 19-37-02](https://user-images.githubusercontent.com/649340/28131283-b830cd9c-6739-11e7-96aa-fc428cc0073b.png)

**Comment by AlexWayfer** [comment] 2017-07-12 18:26
> Of course there needs to be a nice slider (Gtk.Hscale) for setting the level of transparency :smile:.

No… I mean, you choose just one color — `blue`, for example. And borders has 0% of transparency, and background has 50%, for example. But they're both `blue`, with the same color, chosen once and one time.

**Comment by AlexWayfer** [comment] 2017-07-16 16:18
Is it duplicate of #21?

_Sent from my Sony E5823 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Closed** 2017-07-18 03:25 UTC
